apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: k8s-helm

data:
  APP_ENV: "development"
  LOG_LEVEL: "INFO"
  MAX_CONNECTIONS: "10"
  REDIS_HOST: "redis.k8s-helm"
  REDIS_PORT: "6379"